### ISSUE TITLE
Ignore the unrecognized locale or export the supported locales

### ISSUE THREAD

**Issue by wscourge** [lbenie/reading-time-estimator#1225]
There's an error thrown now when passing the unrecognized locale to the `readingTime()`. To make it go away, either:

1. Ignore the unrecognized locale, treating it as there was `undefined` passed instead.
2. Export the supported locales so there can be a check made before using the function.

**Comment by lbenie** [comment]
I reproduced the error thanks for pointing it out.

I think this is only possible to trigger if you're using plain javascript without jsdoc.

> Ignore the unrecognized locale, treating it as there was undefined passed instead.

I feel like treating the `locale` as undefined seems wrong and adds unnecessary complexity. With the exported things you should be able to easily tell if a `locale` is supported or not.

I am 💯 relying on `TypeScript` inference / type system here agreed.

> Export the supported locales so there can be a check made before using the function.

These are already exported [here](https://github.com/lbenie/reading-time-estimator/blob/main/lib/index.ts#L1). You can map on the array or do a lookup if the locale is supported or not. Similarly to how I am doing it in my example [here](https://codesandbox.io/s/condescending-rosalind-lll23r?file=/src/App.tsx:1742-1840). 


I think this is a non-issue if you use the exported `supportedLocales` array.

**Comment by wscourge** [comment]
Thank you, I just couldn't find it.
