### ISSUE TITLE
Something wrong about calculating the word counts

### ISSUE THREAD

**Issue by zS1m** [lbenie/reading-time-estimator#1293]
It's me again : )

When I use reading-time-estimator in my blog, I found that the word counts of my article is strange.

So I tested these functions and found that there are some problems about calculating the word counts: 

```javascript
const parseWords = (data) =>
  data.match(/[\w|\d|\s|,|.|\u00C0-\u024F|\u4E00-\u9FA5|\u3041-\u309F]+/giu) ??
  []

const getNumberOfWords = (data) =>
  parseWords(data).reduce(
    (accumulator, word) =>
      accumulator +
      (!word.trim().length ? 0 : word.trim().split(/\s+/u).length),
    0,
  )

const testWords = '中文 多来几个字';

const parsedArr = parseWords(testWords);

const wordCount = getNumberOfWords(testWords);

console.log(parsedArr, wordCount);
// [ '中文 多来几个字' ] 2
```

Unlike English, we generally consider "中文 多来几个字" to have 7 characters. "中文" consists of 2 characters, and "多来几个字" consists of 7. We usually do not use spaces as the standard separator characters. I believe this point also applies to Japanese, so the calculation here has some problems😢

**Comment by lbenie** [comment]
Hey man, I won't be able to look at this until christmas break. I have lots of shit to wrap up before EOY.

If you have some time I'm more than happy to review a PR if you have one!

**Comment by zS1m** [comment]
Hey! Totally get that you've got a lot on your plate, especially wrapping things up before EOY. Thanks for letting me know.

On my end, I haven't come up with a solid solution just yet. If anything clicks, I'll make sure to submit a PR. Best of luck getting everything done before the Christmas break – take some time to relax! Have a good day!
