### ISSUE TITLE
[Bug] Parameters of type ""cn"" cannot be assigned to parameters of type "SupportedLanguages | undefined"

### ISSUE THREAD

**Issue by qcyblm** [lbenie/reading-time-estimator#376]
![image](https://user-images.githubusercontent.com/64412486/143566997-27917d15-a10b-4f3f-963b-448418fc48d6.png)

**Comment by lbenie** [comment]
can you try version `1.4.0` and let me know

**Comment by qcyblm** [comment]
Tried version 1.4.0 and it has resolved successfully
![image](https://user-images.githubusercontent.com/64412486/143663630-00d85ae5-2ee2-4765-9592-b2568f127241.png)

**Comment by lbenie** [comment]
Thanks closing this!
