### ISSUE TITLE
Module not found: Can't resolve 'reading-time-estimator'

### ISSUE THREAD

**Issue by bonesoul** [lbenie/reading-time-estimator#704]
After upgrading from 1.5.3 to 1.6.0 (and later versions), I can't import the lib in my project:

`Module not found: Can't resolve 'reading-time-estimator'`

Using it with node 18.8.0 and importing using: 

`import { readingTime } from **"reading-time-estimator";`

Just downgrading back to 1.5.3 fixes the problem, any ideas?

**Comment by lbenie** [comment]
Interesting, I haven't changed the build process from looking at the release changelog.

I'll debug this later when I get some time!

**Comment by bonesoul** [comment]
my tsconfig.json target is es5 by the way as i'm using the lib in next.js project.

**Comment by bonesoul** [comment]
package.json states:

`  "module": "./dist/reading-time-estimator.es.js",`

but there exists no reading-time-estimator.es.js in dist/ folder.

**Comment by ALWISHARIFF** [comment]
I have the same issue
